CREATE TABLE `barcodes` (
  `processid` varchar(32) NOT NULL DEFAULT '',
  `sampleid` varchar(32) DEFAULT NULL,
  `museumid` varchar(32) DEFAULT NULL,
  `fieldid` varchar(32) DEFAULT NULL,
  `bin_guid` varchar(32) DEFAULT NULL,
  `bin_name` varchar(32) DEFAULT NULL,
  `vouchertype` varchar(32) DEFAULT NULL,
  `inst_reg` varchar(255) DEFAULT NULL,
  `phylum_reg` varchar(255) DEFAULT NULL,
  `class_reg` varchar(255) DEFAULT NULL,
  `order_reg` varchar(255) DEFAULT NULL,
  `family_reg` varchar(255) DEFAULT NULL,
  `subfamily_reg` varchar(255) DEFAULT NULL,
  `genus_reg` varchar(255) DEFAULT NULL,
  `species_reg` varchar(255) DEFAULT NULL,
  `taxonomist_reg` varchar(255) DEFAULT NULL,
  `collectors` varchar(255) DEFAULT NULL,
  `collectiondate` varchar(32) DEFAULT NULL,
  `lifestage` varchar(32) DEFAULT NULL,
  `lat` varchar(32) DEFAULT NULL,
  `lon` varchar(32) DEFAULT NULL,
  `site` varchar(255) DEFAULT NULL,
  `sector` varchar(255) DEFAULT NULL,
  `region` varchar(255) DEFAULT NULL,
  `province_reg` varchar(255) DEFAULT NULL,
  `country_reg` varchar(255) DEFAULT NULL,
  `fundingsrc` varchar(255) DEFAULT NULL,
  `seqentryid` int(11) DEFAULT NULL,
  `seqdataid` int(11) DEFAULT NULL,
  `marker_code` varchar(255) DEFAULT NULL,
  `nucraw` text,
  `aminoraw` text,
  `seq_update` varchar(255) DEFAULT NULL,
  `total_trace_count` int(11) DEFAULT NULL,
  `high_trace_count` int(11) DEFAULT NULL,
  `accession` varchar(32) DEFAULT NULL,
  PRIMARY KEY (`processid`),
  KEY `sampleid` (`sampleid`),
  KEY `museumid` (`museumid`),
  KEY `fieldid` (`fieldid`),
  KEY `bin_guid` (`bin_guid`),
  KEY `bin_name` (`bin_name`),
  KEY `vouchertype` (`vouchertype`),
  KEY `inst_reg` (`inst_reg`),
  KEY `phylum_reg` (`phylum_reg`),
  KEY `class_reg` (`class_reg`),
  KEY `order_reg` (`order_reg`),
  KEY `family_reg` (`family_reg`),
  KEY `subfamily_reg` (`subfamily_reg`),
  KEY `genus_reg` (`genus_reg`),
  KEY `species_reg` (`species_reg`),
  KEY `country_reg` (`country_reg`),
  KEY `accession` (`accession`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
